meta:
    :news_list_header:
        :data_kind: text
        :validations:
            :required: true
            :minLength: null
            :maxLength: 20
        :data_key_name: news_list_header
    :news_list_title:
        :data_kind: text
        :validations:
            :required: true
            :minLength: null
            :maxLength: 500
        :data_key_name: news_list_title
    :news_list_description:
        :data_kind: text
        :validations:
            :required: false
            :minLength: null
            :maxLength: 100
        :data_key_name: news_list_description
    :news_list_image:
        :data_kind: url
        :validations:
            :required: true
            :minLength: null
            :maxLength: null
        :data_key_name: news_list_image
    :news_list_article_link:
        :data_kind: url
        :validations:
            :required: true
            :minLength: null
            :maxLength: null
        :data_key_name: news_list_article_link
    :news_list_date:
        :data_kind: date
        :validations:
            :required: true
            :minLength: null
            :maxLength: null
        :data_key_name: news_list_date

