meta:
    :1:
        :news_list_title:
            :data_kind: text
            :validations:
                :required: true
                :minlength: 5
                :maxlength: 130
            :data_key_name: news_list_title
            :section: news_list
        :news_list_description:
            :data_kind: text
            :validations:
                :required: false
                :minlength: 50
                :maxlength: 500
            :data_key_name: news_list_description
            :section: news_list
        :news_list_image:
            :data_kind: text
            :validations:
                :required: true
                :min_bytes: 1000
                :max_bytes: 100000000
                :accept: image/jpg,image/png,image/jpeg
            :data_key_name: news_list_image
            :section: news_list
        :news_list_article_link:
            :data_kind: url
            :validations:
                :required: false
                :minlength: 3
                :maxlength: 2083
            :data_key_name: news_list_article_link
            :section: news_list
        :news_list_date:
            :data_kind: text
            :validations:
                :required: true
            :data_key_name: news_list_date
            :section: news_list
        :news_list_video_embed:
            :data_kind: url
            :validations:
                :required: false
            :data_key_name: news_list_video_embed
    :2:
        :members_list_title:
            :data_kind: text
            :validations:
                :required: true
                :minlength: 10
                :maxlength: 80
            :data_key_name: members_list_title
        :members_list_name:
            :data_kind: text
            :validations:
                :required: false
                :minlength: 5
                :maxlength: 50
            :data_key_name: members_list_name
        :members_list_image:
            :data_kind: text
            :validations:
                :required: true
                :min_bytes: 1000
                :max_bytes: 100000000
                :accept: image/jpg,image/png,image/jpeg
            :data_key_name: members_list_image

        :members_list_linkedIn:
            :data_kind: url
            :validations:
                :required: false
                :minlength: 3
                :maxlength: 2083
            :data_key_name: members_list_linkedIn
        :members_list_twitter:
            :data_kind: url
            :validations:
                :required: false
                :minlength: 3
                :maxlength: 2083
            :data_key_name: members_list_twitter
        :members_list_medium:
            :data_kind: url
            :validations:
                :required: false
                :minlength: 3
                :maxlength: 2083
            :data_key_name: members_list_medium
        :members_list_website:
            :data_kind: url
            :validations:
                :required: false
                :minlength: 3
                :maxlength: 2083
            :data_key_name: members_list_website
        :members_list_description:
            :data_kind: text
            :validations:
                :required: true
                :minlength: 50
                :maxlength: 500
            :data_key_name: members_list_description



    :3:
        :advisors_list_title:
            :data_kind: text
            :validations:
                :required: true
                :minlength: 10
                :maxlength: 80
            :data_key_name: advisors_list_title
        :advisors_list_name:
            :data_kind: text
            :validations:
                :required: false
                :minlength: 5
                :maxlength: 50
            :data_key_name: advisors_list_name
        :advisors_list_image:
            :data_kind: text
            :validations:
                :required: true
                :min_bytes: 1000
                :max_bytes: 100000000
                :accept: image/jpg,image/png,image/jpeg
            :data_key_name: advisors_list_image
        :advisors_list_linkedIn:
            :data_kind: url
            :validations:
                :required: false
                :minlength: 3
                :maxlength: 2083
            :data_key_name: advisors_list_linkedIn

        :advisors_list_twitter:
            :data_kind: url
            :validations:
                :required: false
                :minlength: 3
                :maxlength: 2083
            :data_key_name: advisors_list_twitter
        :advisors_list_medium:
            :data_kind: url
            :validations:
                :required: false
                :minlength: 3
                :maxlength: 2083
            :data_key_name: advisors_list_medium
        :advisors_list_website:
            :data_kind: url
            :validations:
                :required: false
                :minlength: 3
                :maxlength: 2083
            :data_key_name: advisors_list_website
        :advisors_list_description:
            :data_kind: text
            :validations:
                :required: true
                :minlength: 50
                :maxlength: 500
            :data_key_name: advisors_list_description

    :4:
        :partners_name:
            :data_kind: text
            :validations:
                :required: true
                :minlength: 3
                :maxlength: 50
        :partners_description:
            :data_kind: text
            :validations:
                :required: true
                :minlength: 20
                :maxlength: 500
        :partners_founders:
            :data_kind: text
            :validations:
                :required: true
                :minlength: 5
                :maxlength: 500
        :partners_location:
            :data_kind: text
            :validations:
                :required: true
                :minlength: 3
                :maxlength: 100
        :partners_industry:
            :data_kind: array
            :validations:
                :required: true
        :partners_size:
            :data_kind: text
            :validations:
                :required: true
                :minlength: 5
                :maxlength: 50
        :partners_sprite_index:
            :data_kind: text
            :validations:
                :required: true
        :partners_url:
            :data_kind: url
            :validations:
                :required: true
                :minlength: 3
                :maxlength: 2083
        :partners_twitter:
            :data_kind: url
            :validations:
                :required: false
                :minlength: 3
                :maxlength: 2083
        :partners_medium:
            :data_kind: url
            :validations:
                :required: false
                :minlength: 3
                :maxlength: 2083
        :partners_linkedin:
            :data_kind: url
            :validations:
                :required: false
                :minlength: 3
                :maxlength: 2083
        :partners_on_hover_bgcolor:
            :data_kind: text
            :validations:
                :required: true
            :data_key_name: partners_on_hover_bgcolor
            :section: partners


    :5:
        :careers_title:
            :data_kind: text
            :validations:
                :required: true
                :minlength: 5
                :maxlength: 80
            :data_key_name: careers_title

        :careers_description:
            :data_kind: text
            :validations:
                :required: true
                :minlength: 10
                :maxlength: 500
            :data_key_name: careers_description

        :careers_url:
            :data_kind: url
            :validations:
                :required: true
                :minlength: 3
                :maxlength: 2083
            :data_key_name: careers_url


    :6:
        :careers_title:
            :data_kind: text
            :validations:
                :required: true
                :minlength: 5
                :maxlength: 80
            :data_key_name: careers_title

        :careers_description:
            :data_kind: text
            :validations:
                :required: true
                :minlength: 10
                :maxlength: 500
            :data_key_name: careers_description

        :careers_url:
            :data_kind: url
            :validations:
                :required: true
                :minlength: 3
                :maxlength: 2083
            :data_key_name: careers_url






