default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8
  collation: utf8_unicode_ci
  reconnect: true
  username: pepo
  password: pepo123
  host: 127.0.0.1

<%= Rails.env%>:
  <<: *default
  database: ost_cms_<%= Rails.env%>