default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8
  collation: utf8_unicode_ci
  reconnect: true
  username: <%= ENV['OCA_DEFAULT_DB_USER']%>
  password: <%= ENV['OCA_DEFAULT_DB_PASSWORD']%>
  host: <%= ENV['OCA_DEFAULT_DB_HOST']%>

<%= Rails.env %>:
  <<: *default
  database: ost_cms2_<%= Rails.env %>